version: '3.9'
services:
  flowise:
    image: flowiseai/flowise:latest
    ports:
      - '8610:3000'
    environment:
      - PORT=3000
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
    volumes:
      - flowise_data:/root/.flowise
    restart: unless-stopped
volumes:
  flowise_data:
